import "./JetBrainsMono-Regular.ttf";
import { Button } from "std-widgets.slint";
export global theme {
    in property <bool> dark: true;
    in property <string> font: "JetBrains Mono";
    in property <color> axn-button: theme.dark ? #3c3836 : #ebdbb2;
}

export global elements {
    callback touch(string);
    in property <string> text: " ";
    in property <string> paren;
}

component Button {
    in-out property <string> text;
    in property <color> bg-color;
    in property <length> font-size: 20px;
    in property <color> font-color: theme.dark ? #fbf1c7 : #282828;
    Rectangle {
        min-width: 20px;
        min-height: 15px;
        num := Text {
            text: text;
            font-size: font-size;
            color: font-color;
            font-family: theme.font;
        }

        drop-shadow-color: self.background.darker(theme.dark ? -10% : 10%);
        background: ta.pressed ? bg-color.darker(theme.dark ? -15% : 15%) : ta.has-hover ? bg-color.darker(theme.dark ? -40% : 40%) : bg-color.darker(theme.dark ? -20% : 0%);
        border-radius: ta.pressed ? 8px : 20px;
        border-width: ta.pressed ? 3px : 1px;
        border-color: ta.pressed ? self.background.darker(theme.dark ? -40% : 40%) : self.background.darker(theme.dark ? -22% : 22%);
        animate background, border_radius { duration: 150ms; }
        animate border-width {
            delay: 500ms;
            duration: 2000ms;
            easing: ease-out-elastic;
        }
        ta := TouchArea {
            clicked => {
                elements.touch(num.text);
            }
        }
    }
}

export component AppWindow inherits Window {
    property <length> delta;
    in-out property <length> scroll_offset_x: root.width - text.width;
    property <length> new_scroll_offset;
    property <duration> delay: 100ms;
    property <duration> duration;
    property <bool> left_right: false;
    min-height: 400px;
    min-width: 300px;
    preferred-height: 500px;
    preferred-width: 500px;
    background: theme.dark ? #282828 : #fbf1c7;
    VerticalLayout {
        textArea := Rectangle {
            height: root.height * 40%;
            border-color: red;
            width: root.width;
            padding: -1px;
            text := Text {
                letter-spacing: -0.01px;
                y: parent.height - self.height;
                x: scroll_offset_x;
                height: 55px;
                text: elements.text;
                font-size: 40px;
                color: theme.dark ? #ebdbb2 : #3c3836;
                font-family: theme.font;
                wrap: char-wrap;

                animate x {
                    duration: 100ms;
                    delay: delay;
                    easing: ease-in-out-quad;
                }
            }

            Text {
                letter-spacing: -0.01px;
                y: parent.height - self.height;
                x: scroll_offset_x;
                height: 55px;
                text: elements.paren;
                font-size: 40px;
                color: #fe8019;
                font-family: theme.font;
                wrap: char-wrap;

                animate x {
                    duration: 100ms;
                    delay: delay;
                    easing: ease-in-out-quad;
                }
            }
            left := Rectangle {
                height : 55px;
                x : text.width > root.width && scroll_offset_x <= -1px ? 0 : -30px;
                y : parent.height - self.height;
                width : 30px;
                background: @linear-gradient(90deg, rgba(40,40,40,255) 10%, rgba(40,40,40,0) 100%);
    
                animate x {
                    delay : 100ms;
                     duration : 200ms;
    
                }
                
            }
    
            right := Rectangle {
                height : 55px;
                width : 43px;
                x : scroll_offset_x > root.width - text.width ? root.width - self.width + 3px: root.width;
                y : parent.height - self.height;
                background: @linear-gradient(90deg, rgba(40,40,40,0) 00%, rgba(40,40,40,1) 100%);
                animate x {
                    delay : 100ms;
                    duration : 200ms;
                }
            }

            TouchArea {
                // Handle scroll event
                scroll-event(event) => {
                    new_scroll_offset = scroll_offset_x + event.delta-y / 2;
                    delay = 0ms;
                    duration = 200ms;
                    
                    // Clamp scroll_offset_x to ensure it stays within bounds
                    if root.width > text.width {
                        // If the text fits within the window, keep it aligned to the right
                        reject
                    } else {
                        if new_scroll_offset > 0 {
                            scroll_offset_x = 0;
                        } else if new_scroll_offset < root.width - text.width {
                            scroll_offset_x = root.width - text.width;
                        } else {
                            scroll_offset_x = new_scroll_offset;
                        }
                    }
                    delay = 100ms;
                    duration = 100ms;
                    accept
                }
            }
        }

        Grid := GridLayout {
            padding: 6px;
            height: root.height * 60%;
            spacing: 5px;
            Row {
                Button {
                    bg-color: theme.dark ? #ff403d : #cc241d;
                    text: "C";
                    font-color: root.background;
                    colspan: 1;
                }

                Button {
                    text: "()";
                    bg-color: theme.axn-button;
                    colspan: 2;
                }

                Button {
                    bg-color: theme.axn-button;
                    text: "÷";
                    font-size: 25px;
                    col: 3;
                }
            }

            Row {
                Button {
                    bg-color: root.background;
                    text: "7";
                }

                Button {
                    bg-color: root.background;
                    text: "8";
                }

                Button {
                    bg-color: root.background;
                    text: "9";
                }

                Button {
                    bg-color: theme.axn-button;
                    text: "×";
                    font-size: 25px;
                }
            }

            Row {
                Button {
                    bg-color: root.background;
                    text: "4";
                }

                Button {
                    bg-color: root.background;
                    text: "5";
                }

                Button {
                    bg-color: root.background;
                    text: "6";
                }

                Button {
                    bg-color: theme.axn-button;
                    text: "-";
                    font-size: 25px;
                }
            }

            Row {
                Button {
                    bg-color: root.background;
                    text: "1";
                }

                Button {
                    bg-color: root.background;
                    text: "2";
                }

                Button {
                    bg-color: root.background;
                    text: "3";
                }

                Button {
                    bg-color: theme.axn-button;
                    text: "+";
                    font-size: 25px;
                }
            }

            Row {
                Button {
                    bg-color: root.background;
                    text: ".";
                    font-size: 25px;
                }

                Button {
                    text: 0;
                    bg-color: root.background;
                }

                Button {
                    bg-color: theme.axn-button;
                    text: "<";
                    font-size: 25px;
                }

                Button {
                    bg-color: theme.dark ? #af3a03 : #d65d0e;
                    text: "=";
                    font-color: root.background;
                    font-size: 25px;
                }
            }
        }
    }
}
