import { Button } from "std-widgets.slint";
global theme {
    in property <bool> dark : false;
    in property <string> font-addr;
}
component Button {
    in-out property <string> text;
    in property <color> bg-color;
    in property <length> font-size : 20px;
    in property <color> font-color : theme.dark ? #fbf1c7 : #282828;
    Rectangle {
        Text {
            text: text;
            font-size: font-size;
            color: font-color;
            font-family : "ui/JetBrainsMono-Regular.ttf";
        }

        drop-shadow-color: self.background.darker(theme.dark? -10% : 10%);
        background: ta.pressed ? bg-color.darker(theme.dark? -15% : 15%) : ta.has-hover ? bg-color.darker(theme.dark? -40% : 40%) : bg-color.darker(theme.dark? -20% : 0%);
        border-radius: ta.pressed ? 8px : 20px;
        border-width: ta.pressed ? 3px : 1px;
        border-color: ta.pressed ? self.background.darker(theme.dark? -40% : 40%) : self.background.darker(theme.dark? -22% : 22%);
        animate background, border_radius { duration: 150ms; }
        animate border-width {
            duration: 2000ms;
            easing: ease-out-elastic;
        }
        ta := TouchArea { }
    }
}

// component ActionButton {
//     in-out property <string> text;
//     in property <color> bg-color;
//     in property <bool> dark: true;
//     Rectangle {
//         Text {
//             text: text;
//             font-size: 20px;
//             color: bg-color.darker(theme.dark? -99% : 99%);
//         }

//         drop-shadow-color: self.background.darker(theme.dark? -10% : 10%);
//         background: ta.pressed ? bg-color.darker(theme.dark? -10% : -10%) : ta.has-hover ? bg-color.darker(theme.dark? -40% : 40%) : bg-color.darker(theme.dark? -20% : 20%);
//         animate background, border_radius { duration: 150ms; }
//         border-radius: ta.pressed ? 8px : 20px;
//         border-width: ta.pressed ? 3px : 1px;
//         animate border-width {
//             duration: 2000ms;
//             easing: ease-out-elastic;
//         }
//         border-color: ta.pressed ? self.background.darker(theme.dark? -40% : 40%) : self.background.darker(theme.dark? -22% : 22%);
//         ta := TouchArea { }
//     }
// }

export component AppWindow inherits Window {
    background: theme.dark? #282828 : #fbf1c7;
    VerticalLayout {
        textArea := Rectangle {
            height: root.height * 40%;
            border-color: red;
            width: root.width;
            Text {
                text: root.height / 1px + " x " + root.width / 1px;
                font-size: 32px;
                height: parent.height;
                wrap: char-wrap;
                width: parent.width;
            }
        }

        Grid := GridLayout {
            padding: 6px;
            height: root.height * 60%;
            spacing: 5px;
            Row {
                Button {
                    bg-color: theme.dark? #ff403d : #cc241d;
                    text: "C";
                    font-color: root.background;
                    colspan: 1;
                }

                Button {
                    text: "(";
                    bg-color: root.background;
                }

                Button {
                    bg-color: root.background;
                    text: ")";
                }

                Button {
                    bg-color: root.background;
                    text: "÷";
                }
            }

            Row {
                Button {
                    bg-color: root.background;
                    text: "7";
                }

                Button {
                    bg-color: root.background;
                    text: "8";
                }

                Button {
                    bg-color: root.background;
                    text: "9";
                }

                Button {
                    bg-color: root.background;
                    text: "×";
                }
            }

            Row {
                Button {
                    bg-color: root.background;
                    text: "4";
                }

                Button {
                    bg-color: root.background;
                    text: "5";
                }

                Button {
                    bg-color: root.background;
                    text: "6";
                }

                Button {
                    bg-color: root.background;
                    text: "-";
                }
            }

            Row {
                Button {
                    bg-color: root.background;
                    text: "1";
                }

                Button {
                    bg-color: root.background;
                    text: "2";
                }

                Button {
                    bg-color: root.background;
                    text: "3";
                }

                Button {
                    bg-color: root.background;
                    text: "+";
                }
            }
            Row {
                Button {
                    bg-color: root.background;
                    text: ".";
                }

                Button {
                    bg-color: root.background;
                    text: "<";
                    font-size: 15px;
                }

                Button {
                    bg-color: theme.dark ? #af3a03 : #d65d0e;
                    text: "=";
                    font-color: root.background; 
                    colspan: 2;
                }
            }
            
        }
    }
}
